experiment_name: incbabi_dkaf
destpath: ../models/incbabi_dkaf/
datapath: ../data/incbabi/row_completion/cdnet/

model:
  type: gpt2
  wildcard: gpt2

dataset: babi

train:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 0.00003
  num_epochs: 4
  seed: 42
  fp16: False
  save_eval_steps: 200
  save_total_limit: 5
  metric_for_best_model: dialog_accuracy
  greater_is_better: True
  early_stopping_patience: 5
  warmup_ratio: 0.1

dev:
  per_device_eval_batch_size: 8
  sample: False
  num_beams: 1
  max_resp_length: 26
  top_k: 8
  top_p: 0.9
  temperature: 0.85

use_wandb: True
