experiment_name: incbitod_dkaf
destpath: ../models/incbitod_dkaf/
datapath: ../data/incbitod/row_deletion/cdnet/

model:
  type: gpt2
  wildcard: gpt2

dataset: bitod

train:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 0.00003
  num_epochs: 10
  seed: 44
  # fp16: True
  fp16: False
  save_eval_steps: 100
  save_total_limit: 5
  metric_for_best_model: entity_f1
  greater_is_better: True
  early_stopping_patience: 5
  warmup_ratio: 0.1

dev:
  per_device_eval_batch_size: 4
  sample: False
  num_beams: 1
  max_resp_length: 94
  top_k: 8
  top_p: 0.9
  temperature: 0.85

use_wandb: True
